<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./FloatingIsland-compressed.glb -t -i -u -s -k
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  export const ref = new Group()

  const suspend = useSuspense()

  type GLTFResult = {
    nodes: {
      defaultMaterial: THREE.Mesh
      defaultMaterial001: THREE.Mesh
      defaultMaterial004: THREE.Mesh
      defaultMaterial005: THREE.Mesh
      defaultMaterial006: THREE.Mesh
      defaultMaterial007: THREE.Mesh
      defaultMaterial002: THREE.Mesh
      defaultMaterial003: THREE.Mesh
      defaultMaterial011: THREE.Mesh
      defaultMaterial008: THREE.Mesh
      defaultMaterial009: THREE.Mesh
      defaultMaterial010: THREE.Mesh
    }
    materials: {
      Main_island_1: THREE.MeshStandardMaterial
      Grass: THREE.MeshStandardMaterial
      Mechanic_island1: THREE.MeshStandardMaterial
      Grass_3: THREE.MeshStandardMaterial
      Grass_2: THREE.MeshStandardMaterial
      Merchant_island1: THREE.MeshStandardMaterial
      Side_island: THREE.MeshStandardMaterial
      Grass_4: THREE.MeshStandardMaterial
      SupportBeam_texture_set: THREE.MeshStandardMaterial
      Wood_texture_set: THREE.MeshStandardMaterial
      Platform_texture_set: THREE.MeshStandardMaterial
      Rope_texture_set: THREE.MeshStandardMaterial
    }
  }

  const gltf = suspend(useGltf<GLTFResult>('/FloatingIsland-compressed.glb'))
</script>

<T is={ref} dispose={false} scale={[0.2,0.2,0.2]}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      name="defaultMaterial"
      castShadow
      receiveShadow
      geometry={gltf.nodes.defaultMaterial.geometry}
      material={gltf.materials.Main_island_1}
      material.metalness={0}
      material.color="#ffffff"
    />
    <T.Mesh
      name="defaultMaterial001"
      castShadow
      receiveShadow
      geometry={gltf.nodes.defaultMaterial001.geometry}
      material={gltf.materials.Grass}
      material.side={0}
      material.metalness={0}
      material.color="#ffffff"
      material.envMapIntensity={1}
    />
    <T.Mesh
      name="defaultMaterial004"
      castShadow
      receiveShadow
      geometry={gltf.nodes.defaultMaterial004.geometry}
      material={gltf.materials.Mechanic_island1}
      material.metalness={0}
      material.color="#ffffff"
    />
    <T.Mesh
      name="defaultMaterial005"
      castShadow
      receiveShadow
      geometry={gltf.nodes.defaultMaterial005.geometry}
      material={gltf.materials.Grass_3}
      material.side={0}
      material.metalness={0}
      material.color="#ffffff"
    />
    <T.Mesh
      name="defaultMaterial006"
      castShadow
      receiveShadow
      geometry={gltf.nodes.defaultMaterial006.geometry}
      material={gltf.materials.Grass_2}
      material.side={0}
      material.metalness={0}
      material.roughness={1}
      material.color="#ffffff"
    />
    <T.Mesh
      name="defaultMaterial007"
      castShadow
      receiveShadow
      geometry={gltf.nodes.defaultMaterial007.geometry}
      material={gltf.materials.Merchant_island1}
      material.metalness={0}
      material.color="#ffffff"
      position={[0,0,0]}
    />
    <T.Mesh
      name="defaultMaterial002"
      castShadow
      receiveShadow
      geometry={gltf.nodes.defaultMaterial002.geometry}
      material={gltf.materials.Side_island}
      material.metalness={0}
      material.color="#ffffff"
    />
    <T.Mesh
      name="defaultMaterial003"
      castShadow
      receiveShadow
      geometry={gltf.nodes.defaultMaterial003.geometry}
      material={gltf.materials.Grass_4}
      material.metalness={0}
      material.color="#ffffff"
    />
    <T.Mesh
      name="defaultMaterial011"
      castShadow
      receiveShadow
      geometry={gltf.nodes.defaultMaterial011.geometry}
      material={gltf.materials.SupportBeam_texture_set}
      material.metalness={0}
      material.color="#ffffff"
    />
    <T.Mesh
      name="defaultMaterial008"
      castShadow
      receiveShadow
      geometry={gltf.nodes.defaultMaterial008.geometry}
      material={gltf.materials.Wood_texture_set}
      material.emissive="#000000"
      material.metalness={0}
      material.roughness={1}
      visible
      material.color="#ffffff"
    />
    <T.Mesh
      name="defaultMaterial009"
      castShadow
      receiveShadow
      geometry={gltf.nodes.defaultMaterial009.geometry}
      material={gltf.materials.Platform_texture_set}
      material.metalness={0}
      material.color="#ffffff"
    />
    <T.Mesh
      name="defaultMaterial010"
      castShadow
      receiveShadow
      geometry={gltf.nodes.defaultMaterial010.geometry}
      material={gltf.materials.Rope_texture_set}
      material.metalness={0}
      material.color="#ffffff"
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
