<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./stones2.glb -t -i -u -s -k
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf, useSuspense } from '@threlte/extras'

	export const ref = new Group()

	const suspend = useSuspense()

	type GLTFResult = {
		nodes: {
			Mid_4_MID_0: THREE.Mesh
			Big_5_BiG_0: THREE.Mesh
			Small_8_SMall_0: THREE.Mesh
			Mid_5_MID_0: THREE.Mesh
			BIG_1_BiG_0: THREE.Mesh
			Big_2_BiG_0: THREE.Mesh
			Big_3_BiG_0: THREE.Mesh
			Big_4_BiG_0: THREE.Mesh
			Mid_1_MID_0: THREE.Mesh
			Mid_2_MID_0: THREE.Mesh
			Mid_3_MID_0: THREE.Mesh
			Small_1_SMall_0: THREE.Mesh
			Small_2_SMall_0: THREE.Mesh
			Small_3_SMall_0: THREE.Mesh
			Small_4_SMall_0: THREE.Mesh
			Small_5_SMall_0: THREE.Mesh
			Small_6_SMall_0: THREE.Mesh
			Small_7_SMall_0: THREE.Mesh
			Runic_1_Runic_0: THREE.Mesh
			Runic_2_Runic_0: THREE.Mesh
			Runic_3_Runic_0: THREE.Mesh
			Runic_4_Runic_0: THREE.Mesh
			Runic_5_Runic_0: THREE.Mesh
			Runic_6_Runic_0: THREE.Mesh
			Runic_7_Runic_0: THREE.Mesh
			p1_p1_0: THREE.Mesh
			p2_p2_0: THREE.Mesh
		}
		materials: {
			Mid4: THREE.MeshStandardMaterial
			Big5: THREE.MeshStandardMaterial
			Small8: THREE.MeshStandardMaterial
			Mid5: THREE.MeshStandardMaterial
			Big1: THREE.MeshStandardMaterial
			Big2: THREE.MeshStandardMaterial
			Big3: THREE.MeshStandardMaterial
			Big4: THREE.MeshStandardMaterial
			Mid1: THREE.MeshStandardMaterial
			Mid2: THREE.MeshStandardMaterial
			Mid3: THREE.MeshStandardMaterial
			Small1: THREE.MeshStandardMaterial
			Small2: THREE.MeshStandardMaterial
			Small3: THREE.MeshStandardMaterial
			Small4: THREE.MeshStandardMaterial
			Small5: THREE.MeshStandardMaterial
			Small6: THREE.MeshStandardMaterial
			Small7: THREE.MeshStandardMaterial
			Runic: THREE.MeshStandardMaterial
			material_4: THREE.MeshStandardMaterial
			material_5: THREE.MeshStandardMaterial
		}
	}

	const gltf = suspend(useGltf<GLTFResult>('/stones2.glb'))
</script>

<T
	is={ref}
	dispose={false}
>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			name="Mid_4_MID_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Mid_4_MID_0.geometry}
			material={gltf.materials.Mid4}
			position={[3.74, 0, -0.52]}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Big_5_BiG_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Big_5_BiG_0.geometry}
			material={gltf.materials.Big5}
			position={[13.2936, 2.2, -5.5155]}
			rotation={[0, 0.7854, 0]}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Small_8_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_8_SMall_0.geometry}
			material={gltf.materials.Small8}
			position={[7.31, 0, 4.99]}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Mid_5_MID_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Mid_5_MID_0.geometry}
			material={gltf.materials.Mid5}
			position={[8.3, 0, 0.14]}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="BIG_1_BiG_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.BIG_1_BiG_0.geometry}
			material={gltf.materials.Big1}
			position={[-16.3, 3.8, 3.3]}
			scale={[0.4, 0.4, 0.4]}
			material.wireframe={false}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Big_2_BiG_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Big_2_BiG_0.geometry}
			material={gltf.materials.Big2}
			position={[0.9, 3.3, -3]}
			scale={[0.8, 0.8, 0.8]}
			rotation={[0, 0.2618, 0]}
			visible
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Big_3_BiG_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Big_3_BiG_0.geometry}
			material={gltf.materials.Big3}
			position={[-15.4, 3.7, 2.3]}
			scale={[0.7, 0.7, 0.7]}
			visible
			material.roughness={1}
			material.metalness={0}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Big_4_BiG_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Big_4_BiG_0.geometry}
			material={gltf.materials.Big4}
			position={[-1.7, 3.1, -1.4]}
			visible
			material.metalness={0}
			material.envMapIntensity={1}
			rotation={[0,0.7854,0]}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Mid_1_MID_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Mid_1_MID_0.geometry}
			material={gltf.materials.Mid1}
			position={[-0.2, 2.5, -3.8]}
			visible
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Mid_2_MID_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Mid_2_MID_0.geometry}
			material={gltf.materials.Mid2}
			position={[8.8, 3, 3]}
			visible
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Mid_3_MID_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Mid_3_MID_0.geometry}
			material={gltf.materials.Mid3}
			position={[-2.24, 0, -0.08]}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Small_1_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_1_SMall_0.geometry}
			material={gltf.materials.Small1}
			position={[6.7, 3.1, 1.5]}
			visible
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Small_2_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_2_SMall_0.geometry}
			material={gltf.materials.Small2}
			position={[-0.6, 3.3, 5.3]}
			visible
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Small_3_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_3_SMall_0.geometry}
			material={gltf.materials.Small3}
			position={[-0.2, 3.1, 5.5]}
			visible
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Small_4_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_4_SMall_0.geometry}
			material={gltf.materials.Small4}
			position={[-2.25, 0, 4.94]}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Small_5_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_5_SMall_0.geometry}
			material={gltf.materials.Small5}
			position={[0.7, 0, 4.93]}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Small_6_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_6_SMall_0.geometry}
			material={gltf.materials.Small6}
			position={[3.1, 0, 5.01]}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Small_7_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_7_SMall_0.geometry}
			material={gltf.materials.Small7}
			position={[5.17, 0, 5]}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Runic_1_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_1_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[-5.62, 0, 8.05]}
			visible={false}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Runic_2_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_2_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[-4.48, 0, 7.95]}
			visible={false}
		/>
		<T.Mesh
			name="Runic_3_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_3_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[2.6, 3.4, 7.7]}
			rotation={[0, -0.2618, 0]}
			visible
		/>
		<T.Mesh
			name="Runic_4_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_4_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[0.8337, 3.5, 7.756]}
			rotation={[0, 1.0472, 0]}
			visible
		/>
		<T.Mesh
			name="Runic_5_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_5_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[-0.42, 0, 7.98]}
			visible={false}
		/>
		<T.Mesh
			name="Runic_6_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_6_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[1.17, 0, 8.03]}
		/>
		<T.Mesh
			name="Runic_7_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_7_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[2.65, 0, 8.03]}
		/>
		<T.Mesh
			name="p1_p1_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.p1_p1_0.geometry}
			material={gltf.materials.material_4}
			position={[-1.67, 0, 8.22]}
			visible={false}
			material.color="#ffffff"
		/>
		<T.Mesh
			name="p2_p2_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.p2_p2_0.geometry}
			material={gltf.materials.material_5}
			position={[-1.66, 0, 8.25]}
			visible={false}
			material.color="#ffffff"
		/>
	{:catch error}
		<slot
			name="error"
			{error}
		/>
	{/await}

	<slot {ref} />
</T>
