<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./stones.glb -t -i -u -s -k
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf, useSuspense } from '@threlte/extras'

	export const ref = new Group()

	const suspend = useSuspense()

	type GLTFResult = {
		nodes: {
			Mid_4_MID_0: THREE.Mesh
			Big_5_BiG_0: THREE.Mesh
			Small_8_SMall_0: THREE.Mesh
			Mid_5_MID_0: THREE.Mesh
			BIG_1_BiG_0: THREE.Mesh
			Big_2_BiG_0: THREE.Mesh
			Big_3_BiG_0: THREE.Mesh
			Big_4_BiG_0: THREE.Mesh
			Mid_1_MID_0: THREE.Mesh
			Mid_2_MID_0: THREE.Mesh
			Mid_3_MID_0: THREE.Mesh
			Small_1_SMall_0: THREE.Mesh
			Small_2_SMall_0: THREE.Mesh
			Small_3_SMall_0: THREE.Mesh
			Small_4_SMall_0: THREE.Mesh
			Small_5_SMall_0: THREE.Mesh
			Small_6_SMall_0: THREE.Mesh
			Small_7_SMall_0: THREE.Mesh
			Runic_1_Runic_0: THREE.Mesh
			Runic_2_Runic_0: THREE.Mesh
			Runic_3_Runic_0: THREE.Mesh
			Runic_4_Runic_0: THREE.Mesh
			Runic_5_Runic_0: THREE.Mesh
			Runic_6_Runic_0: THREE.Mesh
			Runic_7_Runic_0: THREE.Mesh
			p1_p1_0: THREE.Mesh
			p2_p2_0: THREE.Mesh
		}
		materials: {
			material: THREE.MeshStandardMaterial
			material_1: THREE.MeshStandardMaterial
			SMall: THREE.MeshStandardMaterial
			Runic: THREE.MeshStandardMaterial
			material_4: THREE.MeshStandardMaterial
			material_5: THREE.MeshStandardMaterial
		}
	}

	const gltf = suspend(useGltf<GLTFResult>('/stones.glb'))
</script>

<T
	is={ref}
	dispose={false}
>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			name="Mid_4_MID_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Mid_4_MID_0.geometry}
			material={gltf.materials.material}
			position={[35.9166,-4.1976,43.0574]}
			rotation={[0, 0, 0]}
			scale={[1.7298, 1.7298, 1.7298]}
			visible
			material.color="#ffffff"
		/>
		<T.Mesh
			name="Big_5_BiG_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Big_5_BiG_0.geometry}
			material={gltf.materials.material_1}
			position={[16.4436,-1.8148,34.9583]}
			rotation={[0,1.1752,0]}
			scale={[2.5693,2.5693,2.5693]}
			visible
		/>
		<T.Mesh
			name="Small_8_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_8_SMall_0.geometry}
			material={gltf.materials.SMall}
			position={[26.299,0.9173,49.4268]}
			visible
		/>
		<T.Mesh
			name="Mid_5_MID_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Mid_5_MID_0.geometry}
			material={gltf.materials.material}
			position={[34.3744,-4.1976,38.0022]}
			rotation={[0, 0, 0]}
			scale={[1.6033, 1.6033, 1.6033]}
			visible
		/>
		<T.Mesh
			name="BIG_1_BiG_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.BIG_1_BiG_0.geometry}
			material={gltf.materials.material_1}
			position={[11.5219,3.6675,17.5066]}
			visible
		/>
		<T.Mesh
			name="Big_2_BiG_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Big_2_BiG_0.geometry}
			material={gltf.materials.material_1}
			position={[5.0476,22.9307,37.1574]}
			visible
		/>
		<T.Mesh
			name="Big_3_BiG_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Big_3_BiG_0.geometry}
			material={gltf.materials.material_1}
			position={[41.8448,-2.3157,20.7571]}
			rotation={[0, 0.0602, 0]}
			scale={[2.4903, 2.4903, 2.4903]}
			visible
		/>
		<T.Mesh
			name="Big_4_BiG_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Big_4_BiG_0.geometry}
			material={gltf.materials.material_1}
			position={[30.8219,-4.1976,31.6022]}
			visible
		/>
		<T.Mesh
			name="Mid_1_MID_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Mid_1_MID_0.geometry}
			material={gltf.materials.material}
			position={[13.0675,9.4663,28.9001]}
			rotation={[0, 0, 0]}
			scale={[2.7583, 2.7583, 2.7583]}
			visible
		/>
		<T.Mesh
			name="Mid_2_MID_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Mid_2_MID_0.geometry}
			material={gltf.materials.material}
			position={[4.9476,11,35.4638]}
			rotation={[0, 0, 0]}
			scale={[1, 1, 1]}
			visible
		/>
		<T.Mesh
			name="Mid_3_MID_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Mid_3_MID_0.geometry}
			material={gltf.materials.material}
			position={[9.3276,-1,30.8869]}
			rotation={[0, 0, 0]}
			scale={[1.5505, 1.5505, 1.5505]}
			visible
		/>
		<T.Mesh
			name="Small_1_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_1_SMall_0.geometry}
			material={gltf.materials.SMall}
			position={[3.0477,51.4168,42.9369]}
			visible
		/>
		<T.Mesh
			name="Small_2_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_2_SMall_0.geometry}
			material={gltf.materials.SMall}
			position={[-13.6983,22.7149,40.0314]}
			visible
		/>
		<T.Mesh
			name="Small_3_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_3_SMall_0.geometry}
			material={gltf.materials.SMall}
			position={[25.9246,23.6026,46.5207]}
			rotation={[0, 0, 0]}
			scale={[12.2374, 4.1069, 14.3491]}
			visible
		/>
		<T.Mesh
			name="Small_4_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_4_SMall_0.geometry}
			material={gltf.materials.SMall}
			position={[31.945,-4.1976,42.8022]}
			visible
		/>
		<T.Mesh
			name="Small_5_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_5_SMall_0.geometry}
			material={gltf.materials.SMall}
			position={[34.895,-4.1976,42.7922]}
			visible
		/>
		<T.Mesh
			name="Small_6_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_6_SMall_0.geometry}
			material={gltf.materials.SMall}
			position={[22.089,0.9173,49.4468]}
			visible
		/>
		<T.Mesh
			name="Small_7_SMall_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Small_7_SMall_0.geometry}
			material={gltf.materials.SMall}
			position={[24.159,0.9173,49.4368]}
			visible
		/>
		<T.Mesh
			name="Runic_1_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_1_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[25.0836,-4.2255,39.0169]}
			visible
		/>
		<T.Mesh
			name="Runic_2_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_2_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[26.2236,-4.2255,38.9169]}
			visible
		/>
		<T.Mesh
			name="Runic_3_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_3_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[27.3136,-4.2255,38.9369]}
			visible
		/>
		<T.Mesh
			name="Runic_4_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_4_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[11.0877,7.4894,52.5159]}
			visible
		/>
		<T.Mesh
			name="Runic_5_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_5_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[25.7095,-4.1976,29.716]}
			rotation={[0, 0, 0]}
			scale={[3.9429, 3.9429, 3.9429]}
			visible
		/>
		<T.Mesh
			name="Runic_6_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_6_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[14.2677,7.4894,52.5459]}
			visible
		/>
		<T.Mesh
			name="Runic_7_Runic_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Runic_7_Runic_0.geometry}
			material={gltf.materials.Runic}
			position={[21.639,0.9173,52.4668]}
			visible
		/>
		<T.Mesh
			name="p1_p1_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.p1_p1_0.geometry}
			material={gltf.materials.material_4}
			position={[29.0336,27.9019,48.5869]}
			rotation={[0, 0, 0]}
			scale={[4.2, 4.2, 4.2]}
			visible
		/>
		<T.Mesh
			name="p2_p2_0"
			castShadow
			receiveShadow
			geometry={gltf.nodes.p2_p2_0.geometry}
			material={gltf.materials.material_5}
			position={[11.4377,7.4894,52.7659]}
			visible
		/>
	{:catch error}
		<slot
			name="error"
			{error}
		/>
	{/await}

	<slot {ref} />
</T>
