<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 -t -i -k cylinder.glb
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Cylinder: THREE.Mesh
		}
		materials: {}
	}

	const gltf = useGltf<GLTFResult>('/cylinder.glb')
</script>

<T
	name="Cylinder"
	is={ref}
	dispose={false}
	position={[-4.6144, -1.2, -0.3]}
	rotation={[0.5088, 0.3541, -0.5378, 'XYZ']}
>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			name="Cylinder"
			geometry={gltf.nodes.Cylinder.geometry}
			material={gltf.nodes.Cylinder.material}
			material.roughness={0}
			position={[0.743, 0.0042, -0.1478]}
		/>
	{:catch error}
		<slot
			name="error"
			{error}
		/>
	{/await}

	<slot {ref} />
</T>
