<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 -t -i -k drop.glb
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Cone: THREE.Mesh
		}
		materials: {}
	}

	const gltf = useGltf<GLTFResult>('/drop.glb')
</script>

<T
	name="Drop"
	is={ref}
	dispose={false}
	position={[0.1617, 2.8192, 1.5197]}
>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			name="Cone"
			geometry={gltf.nodes.Cone.geometry}
			material={gltf.nodes.Cone.material}
			material.roughness={0}
			position={[-3.5563, 0.6906, 1.8159]}
			rotation={[-0.0078, 0.0094, 0.0686, 'XYZ']}
			scale={2.4838}
		/>
	{:catch error}
		<slot
			name="error"
			{error}
		/>
	{/await}

	<slot {ref} />
</T>
