<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 -t -i -k ico.glb
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Icosphere: THREE.Mesh
		}
		materials: {}
	}

	const gltf = useGltf<GLTFResult>('/ico.glb')
</script>

<T
	name="Ico"
	is={ref}
	dispose={false}
	position={[0.3799, 2.0828, -0.9336]}
	scale={1.5893}
	rotation={[0.2337, -0.0256, 0.0327, 'XYZ']}
>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			name="Icosphere"
			geometry={gltf.nodes.Icosphere.geometry}
			material={gltf.nodes.Icosphere.material}
			material.roughness={0}
		/>
	{:catch error}
		<slot
			name="error"
			{error}
		/>
	{/await}

	<slot {ref} />
</T>
