<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 -t -i -k pie-chart.glb
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Cylinder: THREE.Mesh
		}
		materials: {}
	}

	const gltf = useGltf<GLTFResult>('/pie-chart.glb')
</script>

<T
	name="Pie"
	is={ref}
	dispose={false}
	position={[0.2878, 0.4949, -2.3336]}
	rotation={[-1.3847, 0.6804, -1.5189, 'XYZ']}
	scale={1.6696}
>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			name="Cylinder"
			geometry={gltf.nodes.Cylinder.geometry}
			material={gltf.nodes.Cylinder.material}
			rotation={[-0.0486, -0.5551, 0.2805, 'XYZ']}
			position={[-0.7973, 0.6, -0.3113]}
			material.roughness={0}
			scale={0.8294}
		/>
	{:catch error}
		<slot
			name="error"
			{error}
		/>
	{/await}

	<slot {ref} />
</T>
