<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 -t ramp.glb
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	type $Props = Props<THREE.Group>
	type $Events = Events<THREE.Group>
	type $Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Cube001: THREE.Mesh
			Cube001_1: THREE.Mesh
		}
		materials: {}
	}

	const gltf = useGltf<GLTFResult>('/ramp.glb')

	const component = forwardEventHandlers()
</script>

<T
	position={[-0.9976, 0.4603, 0.0125]}
	rotation={[0.5198, -0.2332, -0.3783, 'XYZ']}
	name="Ramp"
	is={ref}
	dispose={false}
	{...$$restProps}
	bind:this={$component}
>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			material.roughness={0.1848}
			geometry={gltf.nodes.Cube001.geometry}
			material={gltf.nodes.Cube001.material}
		/>
		<T.Mesh
			rotation={[0, 0, 0, 'XYZ']}
			geometry={gltf.nodes.Cube001_1.geometry}
			material={gltf.nodes.Cube001_1.material}
		/>
	{:catch error}
		<slot
			name="error"
			{error}
		/>
	{/await}

	<slot {ref} />
</T>
