<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 -t -i -k torus.glb
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Torus: THREE.Mesh
		}
		materials: {}
	}

	const gltf = useGltf<GLTFResult>('/torus.glb')
</script>

<T
	name="Torus"
	is={ref}
	dispose={false}
	position={[-4.5725, 1.5604, 1.676]}
	rotation={[0.3834, -0.1213, -0.5494, 'XYZ']}
	scale={2.2515}
>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			name="Torus"
			geometry={gltf.nodes.Torus.geometry}
			material={gltf.nodes.Torus.material}
			material.metalness={1}
			position={[1.0181, -1.2199, -0.4932]}
			material.roughness={0}
		/>
	{:catch error}
		<slot
			name="error"
			{error}
		/>
	{/await}

	<slot {ref} />
</T>
