<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 -t torus.glb
-->

<script lang="ts">
	import type * as THREE from 'three'
	import { Group } from 'three'
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	type $Props = Props<THREE.Group>
	type $Events = Events<THREE.Group>
	type $Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

	export const ref = new Group()

	type GLTFResult = {
		nodes: {
			Torus: THREE.Mesh
		}
		materials: {}
	}

	const gltf = useGltf<GLTFResult>('/torus.glb')

	const component = forwardEventHandlers()
</script>

<T
	position={[1.2711, 0.2, 0]}
	visible={true}
	name="Torus"
	is={ref}
	dispose={false}
	{...$$restProps}
	bind:this={$component}
>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			material.roughness={0.25}
			geometry={gltf.nodes.Torus.geometry}
			material={gltf.nodes.Torus.material}
		></T.Mesh>
	{:catch error}
		<slot
			name="error"
			{error}
		/>
	{/await}

	<slot {ref} />
</T>
